name: learn-github-actions1
run-name: ${{ github.actor }} is learning Github Actions2
on: [push]
jobs:
  jobs1:
    runs-on: ubuntu-latest
    steps:
      - run: echo 1
  jobs2:
    runs-on: ubuntu-latest
    steps:
      - run: echo 2
